#!/usr/bin/env bash
# This installs nginx and configure it to listen on port 80
# print or return string "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
