#!/usr/bin/env bash
# This Displays the contents of the file `/etc/passwd`.
#   This displays the username, user-id, and home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
